### PR TITLE
Prepare files for translation

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi! I made this PR to prepare your app to translations. When you add new strings in the future please don't forget to surround them with `_( )` to make them translatable.

For now I made it for all the available strings.

I have separated main translations from the metadata translations for more clarity. Metadata translations are now in the `extra` folder.

Finally I updated the translations files with all the available languages.

Let me know if you have any questions. Once you'll have merge this PR I will be able to add French translations. :smile:

PS: Great app :+1: 

**This PR is ready for review**

### CODE REVIEW

**Comment by avojak** [comment]
Hey, sorry it took me a while to respond to this PR. Great reminder about making the strings translatable, that's definitely something I need to do. I'm going to hold off on merging this for now though, since I will likely be changing a lot of the strings still (I haven't put a lot of thought into the wording of things in the app, I've been mostly focused on functionality).

Having French translations would be fantastic! I'm going to leave this PR open, so that minimally in the future I remember to reach out if you're still interested in doing French translations.

Thanks for your interest in the app!

**Comment by NathanBnm** [comment]
@avojak I just fixed the existing conflicts.

When you add new strings in the future could you please don't forget to surround them with _( ) to make them translatable? (Even if it's not for now).

**Review by avojak — APPROVED** [review]

**Comment by avojak** [comment]
Thank you! I'll do my best to remember to wrap strings with _() going forward!

**Comment by avojak** [comment]
@NathanBnm The app recently had its 1.0.0 release, so it's definitely at the point where it could use translations if you're still interested!

**Pull request merged**
